# Generated by Django 5.2 on 2025-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
        ('user', '0004_user_crops_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crops_interest',
            field=models.ManyToManyField(blank=True, related_name='interested_crop', to='crop.crop', verbose_name='兴趣作物'),
        ),
    ]
