# Generated by Django 5.2 on 2025-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
        ('user', '0007_alter_user_crops_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crops_interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_users', to='crop.crop', verbose_name='关注的作物'),
        ),
    ]
