# Generated by Django 5.2 on 2025-09-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='参数名称')),
            ],
            options={
                'verbose_name': '气象参数',
                'verbose_name_plural': '气象参数',
                'db_table': 'xm_disaster_parameter',
            },
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '灾害类型',
                'verbose_name_plural': '灾害类型',
                'db_table': 'xm_disaster_type',
            },
        ),
        migrations.CreateModel(
            name='DisasterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level_name', models.CharField(db_index=True, max_length=32, verbose_name='等级名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='等级描述')),
                ('disaster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.disastertype', verbose_name='关联灾害类型')),
            ],
            options={
                'verbose_name': '灾害等级',
                'verbose_name_plural': '灾害等级',
                'db_table': 'xm_disaster_level',
            },
        ),
        migrations.CreateModel(
            name='DisasterJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('time_scope', models.JSONField(blank=True, help_text='JSON格式存储不同类型灾害的时间范围', null=True, verbose_name='时间范围')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='灾情名称')),
                ('detail_crop_type', models.CharField(blank=True, help_text="用于记录品种信息（如'巨峰葡萄'）", max_length=64, null=True, verbose_name='所属具体的作物类型')),
                ('detail_growth_name', models.CharField(blank=True, help_text="品种特有的生长阶段（如'赤霞珠转色期'）", max_length=64, null=True, verbose_name='所属作物详细生长周期名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='灾情描述')),
                ('formula', models.TextField(blank=True, help_text='python表达式，使用DisasterParameter中的参数', null=True, verbose_name='灾情公式')),
                ('emergency_measure', models.TextField(blank=True, null=True, verbose_name='应急措施')),
                ('Growth_Disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disaster_judgments', to='crop.growth', verbose_name='所属作物生长周期')),
                ('disaster_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judgments', to='forecast.disasterlevel', verbose_name='灾害等级')),
                ('formula_parameters', models.ManyToManyField(help_text='选择公式中使用的气象参数', related_name='judgment_parameters', to='forecast.disasterparameter', verbose_name='公式参数')),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.disastertype', verbose_name='灾害类型')),
            ],
            options={
                'verbose_name': '灾害',
                'verbose_name_plural': '灾害',
                'db_table': 'xm_disaster_judgment',
            },
        ),
    ]
