# Generated by Django 5.2 on 2025-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_disasterparameter_disastertype_disasterlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterjudgment',
            name='time_scope',
            field=models.CharField(blank=True, help_text='存储不同类型灾害的时间范围', max_length=64, null=True, verbose_name='时间范围'),
        ),
    ]
