# Generated by Django 5.2 on 2025-05-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='城市名称')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'xm_city',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('begin_time', models.DateField(verbose_name='开始日期')),
                ('end_time', models.DateField(verbose_name='结束日期')),
                ('crop_class', models.CharField(max_length=64, verbose_name='作物名称')),
                ('growth_cycle', models.CharField(max_length=64, verbose_name='成长周期')),
                ('city', models.ForeignKey(default='get_default_city_id', on_delete=django.db.models.deletion.PROTECT, to='crop.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '作物',
                'verbose_name_plural': '作物',
                'db_table': 'xm_crop',
            },
        ),
    ]
