# Generated by Django 5.2 on 2025-08-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('crop_class', models.CharField(max_length=64, verbose_name='作物类别')),
                ('crop_img', models.ImageField(blank=True, null=True, upload_to='crop_img', verbose_name='作物图片')),
            ],
            options={
                'verbose_name': '作物',
                'verbose_name_plural': '作物',
                'db_table': 'xm_crop',
            },
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('growth_cycle', models.CharField(blank=True, max_length=64, null=True, verbose_name='成长周期')),
                ('begin_time', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('growth_temp_min', models.FloatField(blank=True, null=True, verbose_name='最低适宜温度(℃)')),
                ('growth_temp_max', models.FloatField(blank=True, null=True, verbose_name='最高适宜温度(℃)')),
                ('growth_humidity_min', models.FloatField(blank=True, null=True, verbose_name='最低适宜湿度(%)')),
                ('growth_humidity_max', models.FloatField(blank=True, null=True, verbose_name='最高适宜湿度(%)')),
                ('growth_rainfall_min', models.FloatField(blank=True, null=True, verbose_name='最低适宜降雨量(mm)')),
                ('growth_rainfall_max', models.FloatField(blank=True, null=True, verbose_name='最高适宜降雨量(mm)')),
                ('growth_wind_min', models.FloatField(blank=True, null=True, verbose_name='最低适宜风速(m/s)')),
                ('growth_wind_max', models.FloatField(blank=True, null=True, verbose_name='最高适宜风速(m/s)')),
                ('sunshine_hours_min', models.FloatField(blank=True, null=True, verbose_name='最短日照时长(h)')),
                ('sunshine_hours_max', models.FloatField(blank=True, null=True, verbose_name='最长日照时长(h)')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_growth', to='crop.crop', verbose_name='作物')),
            ],
            options={
                'verbose_name': '该生长周期的作物适宜条件',
                'verbose_name_plural': '该生长周期的作物适宜条件',
                'db_table': 'xm_crop_growth',
            },
        ),
        migrations.CreateModel(
            name='PlantArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=64, verbose_name='名称')),
                ('including_areas', models.CharField(default='', max_length=64, verbose_name='包含的种植区域')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('area', models.FloatField(verbose_name='面积(万亩)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_plant', to='user.city', verbose_name='城市')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plant', to='crop.crop', verbose_name='种植作物')),
            ],
            options={
                'verbose_name': '种植区',
                'verbose_name_plural': '种植区',
                'db_table': 'xm_plant_area',
                'unique_together': {('crop', 'city', 'longitude', 'latitude')},
            },
        ),
    ]
